INSERT INTO student(name, email, gpa)  VALUES ('Sandeep Koirala', 'sndpkrl007@gmail.com', '3.86')
INSERT INTO student(name, email, gpa)  VALUES ('Rajeev Gyawali', 'rajiv.gyawali@gmail.com', '3.96')
INSERT INTO student(name, email, gpa)  VALUES ('Saroj Dev', 'saroz.me@gmail.com', '3.76')
INSERT INTO student(name, email, gpa)  VALUES ('Prabeen Soti', 'sotibhai@gmail.com', '3.92')
INSERT INTO student(name, email, gpa)  VALUES ('Saurav Shrestha', 'sauravbabu@gmail.com', '3.20')
INSERT INTO student(name, email, gpa)  VALUES ('Binod Pant', 'pantb@gmail.com', '3.98')